[package]
name = "distinct"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.4", features = ["multipart"] }
log = "0.4.27"
tokio = { version = "1.47.1", features = ["full"] }
